### ISSUE TITLE
Implement streaming

### ISSUE THREAD

**Issue by jimmywarting** [deanm/omggif#17]
I don't know what the structure gif binaries have, but unless gif requires some headers of how many frames are included in the beginning i would like to request a streaming functionality if it would be possible

In browser you would have to do it with ReadableStream
I would like for this to be able to run in the browser, so i would like to give you an example of what i would like to have 

```js
// Since the stream api don't include Readable stream we would
// instead have to use the readable stream. It works the same way roughly 

var frameReader = new ReadableStream({
  // gifWriter is gona consume this readableStream
  // and for each time gifWriter call `rs.getReader().read()` 
  // it will call this pull function and ask for a new frame
  pull(controller) {
    if ( last_frame() ) return controller.close() // end the gif

    var url = 'http://example.com/frame_02'
    return fetch(url).then(res => res.arrayBuffer())
  }
})

var gifReadableStream = omggif.gifWriter(frameReader)







// How you would consume the stream

// higher level of abstraction to concatenate all chunks
new Response(gifReadableStream).arrayBuffer().then(buffer => {
  var blob = new Blob([buffer], {type: "image/gif"})
  // do something with the blob
})

// lower level to consume all chunks
var reader = gifReadableStream.getReader()
var pump = () => {
  reader.read().then(result => {
    // one chunk is the same as if you would add a frame and
    // get back what has been compiled into a gif frame
    var chunk = result.value
 
    // store or upload chunk in filesystem or the server

    // calling pump here would actually result in the pull function above being executed
    // this would mean omggif don't withheld any memory as everything is getting 
    // piped from a input stream to a output stream
    if (!result.done) pump() 
  })
}
pump()
```

This would allow you to save more memory and build much larger gifs

**Comment by deanm** [comment]
I'm not convinced that memory usage is a bottleneck in 2016-era GIF creation.  You can easily allocate more than 1gb of memory from a JavaScript process.  Are you actually having an situation where you are hitting an OOM?  Or what exact problem are you trying to solve?  I think instead of proposing the API that you want, it would be better to submit an example that currently doesn't run or runs poorly, and then figure out the best solution to that problem.

While it would be quite easy to implement a frame-at-a-time writing approach, I just don't really think you'll see any measurable benefit from it, especially considering the network etc, I think the actual GIF writing is a tiny fraction of the latency.  If you are trying to do webcam-like streaming, then GIF is not the right choice anyhow.

**Comment by deanm** [comment]
Also see previous discussion on streaming:

https://github.com/deanm/omggif/issues/14#issuecomment-137668060

I think if you benchmark it non-streaming will win over streaming in every likely scenario.

**Comment by jimmywarting** [comment]
I'm not using fetch... it was but an example of a asyncronus call that returns a promise...

I have just been trying to help a little fellow in my [library](https://github.com/jimmywarting/StreamSaver.js/issues/38) He was having an issue with 70 800x800 frames and the memory went up a lot 

He used gifshot and they had a dependencies on your lib
the problem was that he was allocating all images at once and that could make his app crash.
I just think it would be cool to have some streaming functionality. A frame-by-frame approach
That would make it work grate towards my StreamSaver lib also

Imagine having omggif as a tool on a node server and you had many request at once... it can add up alot

**Comment by jimmywarting** [comment]
ok, i read your other comment now about streaming and browserify and @bfred-it streaming. It did add up a bit. 

But just a simpler frame-by-frame functionality could be useful don't have to be a web stream or a node stream. just something that lets us adopt the function do build a web stream or a node stream.

**Comment by deanm** [comment]
"Imagine having omggif as a tool on a node server and you had many request at once... it can add up alot"

This is not really how it works, Node is effectively single threaded (or maybe now there is some thread pool but still the same idea would apply).  You are only serving a single request at a time, so you don't have those requests "at once", you have some waiting, and you have a single one you are serving, and then when you are done you service the next, etc.

The question comes down to where the source frame data is coming from.  If this is coming from a webcam or something, then they need to be buffered somewhere, somehow, until they can make it out across the network.  So they are either sitting in memory uncompressed, or they are sitting in the GIF output compressed.  The latter clearly seems like the better option.

In the bug you listed, if the file is 22MiB on disk, then it will also be 22MiB of `omggif`'s memory.  If there is memory usage beyond that, that has to do with the client application and not with `omggif`, and I have a feeling streaming won't make any difference there.

If you want to make your own modification to `GifWriter`, you can just add a method to reset p to 0.  This will start writing again at the beginning of the buffer.  You can use this to implement your own frame-at-a-time approach, addFrame will write to `buf` starting at `p`.  If you reset `p` to `0` it will just start writing again at the beginning of the buffer.  So you can `addFrame`, do whatever you want with it wrote, set `p` to `0` and repeat.  This means you will have roughly a single frame in memory at a time.  However, it now means you have to wait on the network before continuing to the next frame, etc.

I guess that means from `GifWriter`'s perspective, I could add a way of getting / setting / zeroing `p`, otherwise I don't think there is much else that should be done on `omggif`'s side.

**Comment by deanm** [comment]
Just want to clarify again about memory usage.  `omggif` doesn't really allocate memory, you pass in the memory as `buf` to `GifWriter`.  This buffer only needs to be as big as the final GIF.  So basically `omggif` uses as much memory as the final GIF file will be.  If `omggif` is actually writing out a full 1gb of memory that means you're going to have a 1gb gif file.  In the use case bug you reported, this is for some mobile device application.  If you are trying to upload a 1gb gif file from a phone I think `omggif` is not going to be your problem...

**Comment by bfred-it** [comment]
Just to add to the memory usage: yes, it's still a problem in 2016 and will be next year too. I actually stumbled across omggif last year when trying to fix a browser crash my team was having with another library. There was a hard limit of frames I could add before my iPhone's safari crashed the tab. Yes, the entire site crashed.

I've been thinking about that discussion since (no joke), and I think the problem was not gonna be completely solved by streams anyway, since whatever you generate is still gonna end up in memory. 

Something that would help though is a frame-by-frame generation, so at least you don't have to allocate all the frames in memory before even starting, but you could generate them on canvas as they are needed and GC'd as you go

**Comment by deanm** [comment]
@bfred-it I don't know what you're talking about, the omggif API has always been frame by frame.  The main method is addFrame(), which compresses and writes out a single frame.  There is no requirement to have all of the frames generated before creating the gif, and in fact there is no multi-frame methods, you always build the GIF a single frame at a time.

**Comment by deanm** [comment]
@bfred-it Take a look at different examples using omggif, ie the many years old:

https://dl.dropboxusercontent.com/u/7508542/sandbox/omggif/index.html

It draws to a canvas, writes the canvas to GIF using addFrame, and repeats.  There is only ever a single canvas and there are not multiple uncompressed frames stored.  The frame gets compressed to GIF when addFrame is called.

**Comment by jimmywarting** [comment]
Okey so if you don't want to have streaming functionality due to differences in streaming api and more complexity could you just add a new feature/method that emits when the buffer is full so i'm responsible for taking care of the buffer when it's full so that i can flush it somewhere and when i say it's clear you will reset `p` to `0` and continue? That is all i ask for.

```js
var buffer = new ArrayBuffer(1024 * 1024 * 5) // Allow omggif to use this much allocated memory
var gif = new GifWriter( buffer, canvas.width, canvas.height, { loop: 0 } );
gif.onfull = function(done){
   // flush buffer to some place i can store it
   streamSaver.write(new Uint8Array(buffer))
   done() // continue writing 
}
```

**Comment by deanm** [comment]
```
diff --git a/omggif.js b/omggif.js
index 1ae07b5..a8d0264 100644
--- a/omggif.js
+++ b/omggif.js
@@ -206,6 +206,11 @@ function GifWriter(buf, width, height, gopts) {
     }
     return p;
   };
+
+  this.getOutputBuffer = function() { return buf; }
+  this.setOutputBuffer = function(v) { buf = v; }
+  this.getOutputBufferPosition = function() { return p; }
+  this.setOutputBufferPosition = function(v) { p = v; }
 }
 
 // Main compression routine, palette indexes -> LZW code stream.

```

This way when you can always have a buffer allocated big enough for addFrame(), after addFrame you can check how much was written to the buffer (by checking getOutputBufferPosition), and then you can copy that data out wherever you want, and call setOutputBufferPosition(0) so that the next call of addFrame() starts writing to the buffer again at the beginning.

I think this is the only approach that would make sense.

**Comment by bfred-it** [comment]
@deanm my bad, I had forgotten about that 😅
