### ISSUE TITLE
Combine frames with transparency

### ISSUE THREAD

**Issue by photopea** [deanm/omggif#21]
I am trying to get all frames from GIF using decodeAndBlitFrameRGBA() . 

If I "reuse" the image from frame N to N+1, pixels are never removed (problem with spongebob).
![spongebob](https://user-images.githubusercontent.com/15955558/30788339-19484f2e-a19b-11e7-9ac7-69562fba55b7.gif)

If I give an empty image to each call, some frames contain only "difference" (problem with a pizza guy).
![wahneddlgjrz](https://user-images.githubusercontent.com/15955558/30788351-4fea877c-a19b-11e7-8da0-19c50e30a06d.gif)

What should I do?

**Comment by deanm** [comment]
It depends on the "disposal" of the frame, the GIF spec has more details, but as a very simple and not complete example:

https://github.com/deanm/omggif/blob/master/plask_viewer.js#L30

**Comment by photopea** [comment]
What about building this into omggif, so users don't have to care about any "disposal"?

**Comment by deanm** [comment]
I don't really think this fits into omggif, because for example how you handle transparency, how you clear your output to a solid color, etc, these are things that are usually handled in whatever specific system (<canvas>, etc) you are using, and not something to be handled by omggif itself, otherwise I would have handled it there.  See the plask viewer as an example, omggif can't know about the clear() method on Plask's canvas, etc.
