### ISSUE TITLE
Get global palette from GIF

### ISSUE THREAD

**Issue by stalgiag** [deanm/omggif#35]
Apologies if this should be more obvious but is there a way to get the global palette buffer from GIFReader? 

I am decoding GIFs into RGBA frames and then later want to encode the frames back into a GIF. I can't do this without a palette for obvious reasons but I am having trouble understanding what GIFWriter wants as the palette.

I am currently passing in something that is effectively made like this:
```
var globalPalette = arrayBuffer.slice(
  gifReader.global_palette_offset,
  gifReader.global_palette_size + offset
);
```
But I get the `Invalid code/color length, must be power of 2 and 2` error. Any tips are greatly appreciated!

**Comment by stalgiag** [comment]
I realize that I don't actually have access to those variables in a useful format. I also realized that if I can reliably assume that the palette isn't local that I can get this via the first frame with:
```
globalPalette = arrayBuffer.slice(
      gifReader.frameInfo(0).palette_offset,
      palette_size + palette_offset
 );
```
If those assumptions are correct and that is the correct format for passing to GIFWriter's `gopts.palette` then I think I solved this problem. I am still unable to get the correct data out of GIFWriter but I think that solves the palette problem.

**Comment by stalgiag** [comment]
Okay the above was wrong I am now realizing but I still have no idea to extract something that I can use as a palette later when writing. I would expect this to work but it gives corrupted results:
```
    var gifReader = new omggif.GifReader(arrayBuffer);
    var paletteOffset = gifReader.frameInfo(0).palette_offset;
    var paletteEnd = paletteOffset + gifReader.frameInfo(0).palette_size * 3;
    var paletteSeparated = arrayBuffer.slice(paletteOffset, paletteEnd);
    var paletteCombined = [];
    for (var i = 0; i < paletteSeparated.length; i += 3) {
      var r = paletteSeparated[i] & 0xff;
      var g = paletteSeparated[i + 1] & 0xff;
      var b = paletteSeparated[i + 2] & 0xff;
      var rgb = (r << 16) | (g << 8) | b;
      paletteCombined.push(rgb);
    }
```

**Comment by deanm** [comment]
I am not sure I completely followed everything, but just a few starting points that might help.  The GIF format allows for (an optional) global palette, and then additionally individual frames can have a local palette.  The GIFReader frame structure will basically have a pointer to whatever palette should be used (global or local), this is the frame.palette_offset.  So if you're trying to base an output GIF's palette based on some input GIF's palette you might have to deal with the possibility of the input having multiple palettes (from frame local palettes).  You should just be able to run through all the frames and see if all of the frame.palette_offset's (and sizes I suppose) are the same, then you know there is one single palette. Note: You did something like gifReader.global_palette_offset but global_palette_offset is not a property on gifReader, it is not exported, it is just a local variable used in the process of creating all of the frames.

I'm a bit confused by the name arrayBuffer, because if I remember correctly you cannot access an arrayBuffer's data with the array syntax ([ ]), you need to use a DataView / one of the typed arrays, so I am not actually following what you are doing with paletteSeparated since it looks from the code it will be an ArrayBuffer and so your access of paletteSeparated[i] will always returned undefined.

Otherwise you are right on realising that the GifWriter takes a palette of RGB in a single 24-bit value (versus having an array * 3 or array of arrays, etc).  This is maybe a bit awkward but it's common in graphics and especially in JavaScript it reduces the number of "objects" by 1/3rd.  These RGB values then get unpacked and written out into 3 bytes in GifWriter.

**Comment by stalgiag** [comment]
Ah thanks yeah I figured it out shortly after writing that mess of confusion. Thank you for the helpful reply and fast library!

**Comment by thewayur** [comment]
> Ah thanks yeah I figured it out shortly after writing that mess of confusion. Thank you for the helpful reply and fast library!

can u please provide ur final code/function?

**Comment by stalgiag** [comment]
> 

[You can see this GIF saving code in p5.js.](https://github.com/processing/p5.js/blob/main/src/image/image.js#L187) Though some of that is specific to our use case.
