### ISSUE TITLE
Invalid Block Size

### ISSUE THREAD

**Issue by photopea** [deanm/omggif#39]
I have this GIF, which works in all programs, but OMGGif says "Invalid Block Size" during parsing.

Could you fix it?

![9F55BE88-48F2-4A49-8980-F6F018205C33](https://user-images.githubusercontent.com/15955558/62067033-0ea0b480-b233-11e9-89c1-ee72013da573.gif)

**Comment by deanm** [comment]
From what I can tell from a quick look, it looks like the GIF is truncated.  The file is 393011 bytes, however the last frame specifies another block (at file offset 392874) which means trying to read another block starting at 393128 which is off the end of the file. Other parsers might just use what was parseable, omggif could be made to do this but it would be a pretty significant change to the API, because it would have to be converted to indicate that there was an error but then try to still have whatever was successfully parsed still available (frames, etc).

At the end of the day the GIF looks invalid, please correct me if I'm wrong there.

**Comment by deanm** [comment]
ImageMagick agrees:

```
identify 62067033-0ea0b480-b233-11e9-89c1-ee72013da573.gif 
62067033-0ea0b480-b233-11e9-89c1-ee72013da573.gif[0] GIF 474x469 474x469+0+0 8-bit sRGB 256c 393011B 0.000u 0:00.000
62067033-0ea0b480-b233-11e9-89c1-ee72013da573.gif[1] GIF 474x469 474x469+0+0 8-bit sRGB 256c 393011B 0.000u 0:00.000
62067033-0ea0b480-b233-11e9-89c1-ee72013da573.gif[2] GIF 474x469 474x469+0+0 8-bit sRGB 256c 393011B 0.000u 0:00.000
62067033-0ea0b480-b233-11e9-89c1-ee72013da573.gif[3] GIF 474x469 474x469+0+0 8-bit sRGB 256c 393011B 0.000u 0:00.000
62067033-0ea0b480-b233-11e9-89c1-ee72013da573.gif[4] GIF 474x469 474x469+0+0 8-bit sRGB 256c 393011B 0.000u 0:00.000
62067033-0ea0b480-b233-11e9-89c1-ee72013da573.gif[5] GIF 474x469 474x469+0+0 8-bit sRGB 256c 393011B 0.000u 0:00.000
62067033-0ea0b480-b233-11e9-89c1-ee72013da573.gif[6] GIF 474x469 474x469+0+0 8-bit sRGB 256c 393011B 0.000u 0:00.000
identify: CorruptImage `62067033-0ea0b480-b233-11e9-89c1-ee72013da573.gif' @ error/gif.c/PingGIFImage/935.
```

**Comment by photopea** [comment]
Hi, ok, I see. In my case, people open hundreds of GIFs every day through your library. They see the GIF working (to some degree) in regular viewers, so they expect to be able to edit it.

What if we switched to "read as much data as possible" instead of "explain the error as well as possible"? Meaning, not reporting errors at all, or print a small message into a console, saying that something is wrong?

**Comment by deanm** [comment]
Like I said, it's a significant and non-backwards compatible change to the API.  I don't think that's a good idea right now.  You might try catching the error, trying to rewriting the GIF into something valid, and trying again.  Otherwise at the moment I don't have plans to support invalid GIFs (even if some other programs manage)

**Comment by photopea** [comment]
I am still receiving lots of "truncated" GIFs from users, who would like to work with them in my program. 

Is there any chance I can convince you to implement it? :) There is no need to change the API, you could just fill the damaged frames with a black color.
